### ISSUE TITLE
Pin player while scrolling

### ISSUE THREAD

**Issue by brassmonkey709** [raingart/Nova-YouTube-extension#10]
Starting today there's no option in settings to pin player while scrolling. This is great and can we get it back? Using Safari 15.4 / Tampermonkey. Tried reinstalling the script and no luck!

**Comment by raingart** [comment]
Yes, the "Pin player while scrolling" plugin has been removed in the new release.
Since there are 3 plugins whose functions intersect with the remote one:
 - Custom buttons > popup player
 - Custom buttons > picture-in-picture
 - Comments show in popup / Description show in popup (Stupid names that does not reflect the essence, but I did not come up with anything better)

Which is the same in essence, but completely different in implementation.

Personally, I use the latter. Because I'm tired of slowdowns when scrolling comments. And clicking on the button "[Scroll to top button](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#scroll-to-top)"

Please try them.
The Pin limited to the browser's viewport area. At the same time, the most complex in implementation.

But if they don’t suit you and you really want the Pin, I will return it back in the new release.

**Comment by brassmonkey709** [comment]
Comments show in popup - trying to test this out; option is on but no change on the youtube page.

There's an image in the help file but it's throwing a 404 error -> https://raw.githubusercontent.com/raingart/Nova-YouTube-extension/gh-pages/wiki_images/comments-popup.png

Any tips on how to activate the comment popup? Thanks in advance and btw this script is awesome :)

**Comment by raingart** [comment]
Added screenshots of work:
https://drive.google.com/drive/folders/1a2oh4y6aoE8XQP804pAlenT8Lbad1qWZ?usp=sharing

Perhaps the reason for not working is that you are using Safari. Unfortunately I only tested in chrome/chromium
Unfortunately, I do not have the opportunity to test in MacOS

Perhaps I'll try picture in picture to automatically display when scrolling. To replace the implementation of pin. Or just return the old one.

If you need the Pin right now, you can install an older version and temporarily disable updates.
https://greasyfork.org/en/scripts/433360-nova-youtube?version=1043124

**Comment by raingart** [comment]
if it's easy for you, you can create a list of plugins that don't work for Safari.

Maybe I can fix them if I know about them.

**Comment by cmhrky** [comment]
> Perhaps I'll try picture in picture to automatically display when scrolling. 


This could be nice. But I guess it is not possible to adjust the size in this way.

**Comment by raingart** [comment]
> This could be nice. But I guess it is not possible to adjust the size in this way.

You can check out this prototype?
[nova-extensions_v1.26.0.zip](https://github.com/raingart/Nova-YouTube-extension/files/8599631/nova-extensions_v1.26.0.zip)

In my WM, you can change the size. If everything is ok, then he will become a replacement

**Comment by raingart** [comment]
And don't forget to disable the previous ver. of Nova. They cannot work in parallel.
I forgot to mention this @brassmonkey709

**Comment by cmhrky** [comment]
> 

I am using the script version. How can I download the script.

**Comment by raingart** [comment]
try it
https://gist.github.com/raingart/fca29d3dd664c1d39b51d41a11a689fe/raw/c4f12b73bef7ed0c7d4306d2e8d70ded8600380f/test_pip.user.js

**Comment by raingart** [comment]
> ...and and how can i use it in English?

What language is it in you? Maybe you it can be improved.
The script detects the locale of your browser and uses it if available.
Predefine it while there is no setting.

**Comment by cmhrky** [comment]
> try it https://gist.github.com/raingart/fca29d3dd664c1d39b51d41a11a689fe/raw/c4f12b73bef7ed0c7d4306d2e8d70ded8600380f/test_pip.user.js

It works on the first scroll down. Then scrolling up and scrolling down again doesn't work.

> > ...and and how can i use it in English?
> 
> What language is it in you? Maybe you it can be improved. The script detects the locale of your browser and uses it if available. Predefine it while there is no setting.

It's in Turkish, but it's really bad because it has google translation. I'd love to help with the translation, but I don't have time right now. It would be nice to change the language.

**Comment by raingart** [comment]
I will then remove the Turkish translation completely in the next release

>It works on the first scroll down
I have this problem too. 

I did not find out its causes and solutions accordingly. I believe that the reason is that the browser has a timeout limit through which you can re-display the video in pip.

Since I do not have statistics, I thought that if I do not use Pin, then the rest do not need it. But I was wrong.
I'm interested in your opinion. What to do:
- leave deleted (as it is now)
- return as it was
- replace or add the current prototype.

As you decide?

**Comment by cmhrky** [comment]
I think it should either be the same as before or it could be a new prototype if it works properly.

By the way, when I press the Home button, the next scrolling down works fine.

**Comment by raingart** [comment]
Subsequently, the Council adopted decision [10/1114332119](https://github.com/raingart/Nova-YouTube-extension/issues/10#issuecomment-1114332119) endorsing that resolution.
