### ISSUE TITLE
Description section in popup ?(Gray Background Issues)

### ISSUE THREAD

**Issue by LanGsA0** [raingart/Nova-YouTube-extension#106]
It's hard to see because it's black text on a gray background.
Please give me a guide on what to do. 
The default theme of Windows is light and I don't use dark mode in Chrome.

**Comment by galantra** [comment]
<details>
<summary>*click* Screenshots from my end in order to demonstrate what you mean</summary>

<img src="https://github.com/raingart/Nova-YouTube-extension/assets/52420923/c8163987-70c4-4dde-be1c-5eebb3468457" width="50%">
<img src="https://github.com/raingart/Nova-YouTube-extension/assets/52420923/4ac63997-f585-4aff-8d47-84b4cc6cf665" width="50%">

</details>

I identified the background color, it's `#222`. There are two instances of this in the userscript (one in `${COMMENTS_SELECTOR}`, one in `${DESCRIPTION_SELECTOR}`). You can replace `#222` with `white`.

**Comment by LanGsA0** [comment]
> *click* Screenshots from my end in order to demonstrate what you mean
> I identified the background color, it's `#222`. There are two instances of this in the userscript (one in `${COMMENTS_SELECTOR}`, one in `${DESCRIPTION_SELECTOR}`). You can replace `#222` with `white`.

I changed it to the value you suggested and it looks great.
thanks!!!
I think it's the same version as the one you linked below. The player didn't understand.

               ${DESCRIPTION_SELECTOR} {
                  margin: 0 1%;
                  overflow-y: auto;
                  max-height: 88vh;
                  max-width: 55%;
                  background-color: white;
                  border: 1px solid #333;
                  border-radius: 0 !important;

**Comment by LanGsA0** [comment]
> The version of youtube available to me is outdated. On it everything works correctly. So I can't test correctly. Perhaps the reason is the region or the selective implementation of certain changes for some users. Is your player rounded or square? I have a square.
> 
> Check this version fixes the bug? https://gist.github.com/raingart/12695858bd13e356ac87350edf651193

Thanks for the reply, it's the same version.

// ==UserScript==
// @name            Nova YouTube
// @namespace       https://github.com/raingart/Nova-YouTube-extension/
// @version         0.43.4
// @description     Powerful control on YouTube

Is your player rounded or square? I have a square. -> I don't understand.

**Comment by galantra** [comment]
I've had the same issue with the dark grey background for a couple of months now, if I recall correctly. Since November 2022 maybe, because that's when I searched for a way to auto-activate Youtube Dark Mode (without cookies).

# Old version (`background-color: #222`)

Script: [0.43.4 from Greasyfork](https://greasyfork.org/scripts/433360-nova-youtube/code/Nova%20YouTube.user.js)

Browser: Firefox 117.0

I am never logged in to Youtube, unlike [the other user](https://github.com/raingart/Nova-YouTube-extension/issues/102#issuecomment-1688025693).

Using this version, my default view player has round corners (like https://github.com/raingart/Nova-YouTube-extension/issues/102#issuecomment-1688067156): <img src="https://github.com/raingart/Nova-YouTube-extension/assets/52420923/c7481cfd-0dd1-4e28-8863-496b8903d480" width="50%">


# Beta script (https://gist.github.com/raingart/12695858bd13e356ac87350edf651193)

:sparkles: The commit fixes the background color! It now adapts to the website theme.

Surprisingly, the corners have become rectangular now. (The same happens when I manually set `background-color: white;` in the old script version.)

<img src="https://github.com/raingart/Nova-YouTube-extension/assets/52420923/32f30352-3294-4613-9b55-d62049f9005a" width="50%">

**Comment by raingart** [comment]
@galantra thanks for mentioning what happens if the user is not logged in. I was able to round the preer and reproduce this bug. Strange behavior. If you try to change the player, it automatically becomes square. 
Strange behaviour because I tested it on an installed browser and it was square. And in incognito it has already become round. Apparently takes into account cookies or round storage data

**Comment by galantra** [comment]
Just to clarify: I am not logged in in either scenario. So, to me it doesn't look like the round/square issue is related to that.  
The only change I made was in the Nova Userscript, specifically the color in `${COMMENTS_SELECTOR`} and `${DESCRIPTION_SELECTOR}`. Or, at least, I tried to make sure that it was.

I have a lot of other userscripts and extensions installed and haven't tested it on a fresh browser, so I can't rule out that it is some kind of interaction.
