### ISSUE TITLE
Player Full-viewport disables scrolling

### ISSUE THREAD

**Issue by Doosty** [raingart/Nova-YouTube-extension#11]
Hi im trying to use "Player full-with (theater) mode - Full-viewport" however the youtube video page becomes impossible to scroll down. Using firefox, tampermonkey, latest Nova script.

Ps: Im currently using [ResizeYoutubePlayerToWindowSize](https://github.com/Zren/ResizeYoutubePlayerToWindowSize) which works well and also moves the search header below the video, but it doesnt support mini player when scrolling and other goodies your script has.

**Comment by raingart** [comment]
Yes "pin player" plugin incompatible with [ResizeYoutubePlayerToWindowSize](https://github.com/Zren/ResizeYoutubePlayerToWindowSize)

We both use the same techniques. Moreover, ResizeYoutubePlayerToWindowSize uses more aggressive methods by overlapping pin. I don't think it's possible to make them compatible.
The only option compatible with ResizeYoutubePlayerToWindowSize  is to replace the "pin plugin" css implementation with a picture-in-picture. But he is unstable. So far I haven't been able to bypass [user-trusted events](https://html.spec.whatwg.org/multipage/interaction.html#triggered-by-user-activation).

Scrolling does not work because only because it does not exist Full-viewport works. The non-scroll implementation is very simple and reliable.

As a workaround, I can recommend trying "Full-viewport" + two "section in popup" plugins for comments and video description.

**Comment by Doosty** [comment]
[ImprovedTube](https://improvedtube.com/) BETA on Chrome can create pinned mini player + full window size, but it is bugged on Firefox unfortunately. These options:
- appearance -> player : full window
- appearance -> header : hidden on video page
- player -> custom mini-player

Maybe it can give you some ideas, but i would be happy if you just enabled scrolling with full-window on your extension. Thank you.

**Comment by raingart** [comment]
try [beta ver.](https://openuserjs.org/scripts/raingart/Nova_YouTube)
It added a scroll when activating any (except "Default" item) mode. 

Scrolling is activated when you hover over the player control panel. In order not to conflict with plugins that change the volume and speed of the video. But at the same time, the built-in volume control with the bear wheel stops working.

Additionally fixed item "Full-viewport exit if video ends/pause" which didn't work.

And the plugin itself is again renamed to "Theater mode".
