### ISSUE TITLE
[Feature] Auto-PIP when switching tab

### ISSUE THREAD

**Issue by azhe403** [raingart/Nova-YouTube-extension#113]
Maybe similar with this,
https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#pause-background-tab

but performing PiP mode instead of pause video.

**Comment by raingart** [comment]
Amazing result.
Yes, this functionality exists, but all the code responsible for PiP has been commented out.
https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/player/background-pause.js#L168

Because I was unable to bypass the browser limitation. The browser disallow a number of actions by scripts unless the event is initiated by the user.
I even tried different methods including activating pip buttons, but they all didn't work.

I did a code search. And the only 6 mentions were related to the “Custom player buttons” plugin. Perhaps you have this plugin enabled and the option to add a pip button? 
Can you check if your Nova installed copy has comments or is missing them? What version of the script are you using? Try disabling other scripts and check.

**Comment by raingart** [comment]
I will close the error because it seems to me that it is related to other scripts. Your version may be corrupted. And the comments section does not work correctly
If the error appears regularly, send me the Nova code and the version of the software you are using
