### ISSUE TITLE
Stop video preload - not working, black screen [Bug]

### ISSUE THREAD

**Issue by J4CKED** [raingart/Nova-YouTube-extension#115]
With the option checked "Stop video preload" the movie screen is all black.
(space bar to pause not working too)

 - Browser: Firefox 113.0.2 x64
 - Violentmonkey v2.16.0
 - Nova 0.43.7
https://www.youtube.com/watch?v=biVmlI6pAw8

**Comment by raingart** [comment]
I confirm that there is such a problem
but the error is not related to Nova
If you disable Nova, enter the command `movie_player.stopVideo()` into the browser console, then exactly the same bug occurs

Probably the error is due to a syntax failure on the youtube side

![Screenshot_1](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/55d03e4d-f2c1-4013-9455-237958f9a022)

**Comment by raingart** [comment]
fixed in the new ver.
