### ISSUE TITLE
Page reloading

### ISSUE THREAD

**Issue by J4CKED** [raingart/Nova-YouTube-extension#12]
When I want to display a sample page 
https://www.youtube.com/c/BacktoBlading
The page takes about 10 seconds to load and it looks like it reloads several times. 
During loading sometimes I can see the page, suddenly it disappears, loads again and after a while it reappears.
The same happens when I want to display the playlist in a new window (View full playlist button), for example 
https://www.youtube.com/playlist?list=PLQGRbw6onI2ZgcoOHtzxSsM3NLiaUkG30

Without the script, the page loads correctly.

I'm using Vilolentmonkey, script v0.29, Firefox 93

**Comment by raingart** [comment]
Try disabling some plugins to see which one is the problem. Don't forget to save your old settings if needed.

Probably one of them is the problem:
 - Dark theme by default [?](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#dark-theme)
 - Disable autoplay next video [?](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#video-next-autoplay-disable)
 - Add playlist reverse order button [?](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#playlist-reverse)
 
start with them.

**Comment by J4CKED** [comment]
Disabling "Dark theme by default" fixed my problem. Thank you :)

**Comment by raingart** [comment]
The problem is that these two plugins work by changing cookies

- Dark theme by default [?](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#dark-theme)
- Disable autoplay next video [?](https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#video-next-autoplay-disable)

But the page does not refresh itself. That is, the cookies were loaded/changed, but the page will only change after a reload.

For example, when you enable cleaning cookies when you restart the browser. Every time it will repeat
I had to page reload that if cookies don't match the target.

I pointed out both the title and wiki page about it. But it's probably not clear enough. I think I will remove the first two plugins.

You seem to know Polish if you have the time, desire, then you can make a translation.

**Comment by J4CKED** [comment]
I can give it a try. Do you have any xml file? Or just a translation from the script settings?

**Comment by raingart** [comment]
there are several lines in the plugins

1 `title: `  - [ex. title](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/comments/expand.js#L3) this is the name plugin


2 `label: ` - [ex. label](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/comments/expand.js#L66) is the name option

3 `title: ` - [title](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/comments/expand.js#L92) tooltip on hover

I think translating all plugins is too long and boring. Therefore, it may be worth translating only what is not clear.

you can download .zip replace the value in the files 
or add a new line:
`'label:pl': 'Polish Opis',`

Send the modified files to my email raingart@protonmail.com

Here in English, not everything is clear, and it seems to me that for those who do not understand it well, it will be difficult to figure it out. If something is not clear or there are any suggestions, write, I will try to explain everything I can

**Comment by J4CKED** [comment]
[_youtubescript_polish_translation.zip](https://github.com/raingart/Nova-YouTube-extension/files/8934241/_youtubescript_polish_translation.zip)

I tried to send, but gmail blocks the zip file.
I'm adding it here, maybe it will work.
Check if I did the translation right. I hope so, because there was quite a lot of it. 

I personally prefer English, so could you please add the language setting to the script?

**Comment by raingart** [comment]
Thank you very much I will add it to the new release.
I'll try add a switching language. Now it is tied to the localization of the browser. If you have English, then it will be it
