### ISSUE TITLE
[Bug] Importing settings doesn't work

### ISSUE THREAD

**Issue by SuperBlazer505** [raingart/Nova-YouTube-extension#120]
Before reinstalling Firefox I've made a backup of Nova YouTube settings with script's "Export settings" option.
So now I have nova-settings.json backup file, but I can't import restore it. When I click on "Import settings" it literally doesn't do anything.

 - Browser: Firefox 120.0
 - Violentmonkey 2.16
 - Nova YouTube 0.43.8

**Comment by raingart** [comment]
Thanks, I'll change the import method for Firefox.

the reason is "Interestingly enough and contrary to common sense when I set `InputPickerBlockedNoUserActivation` in `about:config` programmatic .click() magically started to work no matter if the state is `true` or `false`."

p.s. I can congratulate all users of this browser. Now, for “security” purposes, you will manually copy/paste the settings

![Screenshot from 2023-11-29 11-11-15](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/540d04d0-3b02-4d43-83f1-c0ad1bf9fe8c)

**Comment by raingart** [comment]
install beta (click "Raw") https://gist.github.com/raingart/a83804b01b7af45796cbe0a740f7899b

or if you use Violentmonkey, you can directly edit script settings:
![Screenshot from 2023-11-29 11-16-45](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/252a23e6-f747-4390-aff6-f92d99b7dd86)
