### ISSUE TITLE
Comments sort by?

### ISSUE THREAD

**Issue by gabri25ele** [raingart/Nova-YouTube-extension#122]
I don't understand how the Comments sort option works.
If I would like the comment sort always by new to old, How should i do?
In settings there is only the off and on button.

**Comment by raingart** [comment]
It's too difficult to mix inline comments on a page. Therefore, it was easier to create your own loader in the popup. displays the overall comments in table form. Which can already be sorted

https://github.com/raingart/Nova-YouTube-extension/assets/13064767/cda957a8-10c5-43e9-b240-77f2de41c2b6

**Comment by raingart** [comment]
>If I would like the comment sort always by new to old, How should i do?
no way, I'm not going to implement it

In the video above, some replays will not be displayed. This is due to API restrictions and the fact that the specified number of minimum words also applies to replays

![Screenshot from 2023-11-30 18-35-59](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/072f1668-5956-4790-800b-27c06bb1a080)
