### ISSUE TITLE
Opera deletes previously imported Nova folder

### ISSUE THREAD

**Issue by mlkf2014** [raingart/Nova-YouTube-extension#13]
*Opera deletes previously imported Nova folder.
Sorry for my English. But the extension is really great I feel sorry as Opera removes it.
After importing the extension in developer mode, a few settings in the NOVA extension are fine, but after closing Opera and restarting it, the NOVA extension is gone. I pasted the unzipped folder with the NOVA extension into Opera's extensions folder and performed the import in Opera from that location. Perhaps Opera Assistant scans folders after shutdown and removes extraneous folders, I don't know. The folder was named as I unzipped \\Nova-YouTube-extension-master\\1.32.0\\, while folders of other extensions are named, for example, "kdinfjomkigjcjcbigolloleeiianaif"*

 - Browser: Opera 88.0.4412.53_x64
 - Windows 10 HOME x64 21H1
 - Nova zippped version: 1.32.0

**Comment by raingart** [comment]
try using the [userscript version](https://openuserjs.org/scripts/raingart/Nova_YouTube). There are [many mentions](https://forums.opera.com/topic/43422/permanently-resetting-the-extension-settings) on the opera forum. And as a solution, I suggest [reinstalling](https://forums.opera.com/topic/50103/extension-changes-get-deleted-after-i-restart-opera/3?_=1656868583918&lang=en-GB) the browser or checking the file system. Maybe it's in [read-only mode](https://forums.opera.com/topic/50292/installing-and-removing-extensions/3?_=1656869022933&lang=en-GB). Or access restriction

possible solutions:

1. I would recommend creating a 2nd user in the browser. 

1.1 And try to install the extension in it. 

1.2 If after restarting the browser it is not deleted, then the problem is in the browser configuration failure. 

2. If the error persists then try moving the browser to another directory (c:\opera_test). To check access to file-system. 
2.1. If this does not help, then perhaps the opera starts with the debag mode turned off.

3. well, better userscript version to use

**Comment by mlkf2014** [comment]
*Thank you very much for your help.
I did as you advised. I already had the "tampermonkey" extension and NOVA script before but there were some errors and I decided to install NOVA as a separate extension. Indeed, I have problems with permissions on the system and have not yet figured out where the problem is. Windows is just a few days after installation and the latest updates. In spite of this, I keep having problems installing various applications due to limited permissions, even though I have an administrator account.
Perhaps this is a problem after the windows update, it wasn't there before.
Nova is now running as a script in TamperMonkey. 
Again, thank you very much for your help.*
