### ISSUE TITLE
[Feature] Block Additional Icon/Element

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#134]
Add option to hide "[Play on TV](https://i.gyazo.com/3057c63c3d13c69876c5dfb6bb2c15af.png)" button in "Hide player buttons/elements".

**Comment by zkisaboss** [comment]
btw I noticed you've put a lot of effort into this project, and it has been such a positive learning experience for me, so thanks. I just didn't want to see your work go unnoticed.

**Comment by raingart** [comment]
@zkisaboss thank you

This button did not appear for me because it requires certain [flags](https://www.tenforums.com/browsers-email/180538-youtube-play-tv-icon-missing-browsers.html ) to display it 

Maybe `GlobalMediaControls` [my conf](https://github.com/raingart/dotfiles/blob/master/.config/chromium-flags.conf#L30)

beta
https://gist.github.com/raingart/7af5c97a84724c55e2358e5b64712d8e

**Comment by zkisaboss** [comment]
I don't see these flags in chrome://flags/ are they a different kind of flag. If so how do I modify mine to match yours?

**Comment by zkisaboss** [comment]
I had trouble finding the flag that was causing this, but I found a solution. I added the following to my uBlock Origin filters list:

www.youtube.com##.ytp-button.ytp-remote-button
