### ISSUE TITLE
Please add these features

### ISSUE THREAD

**Issue by RitikDixit2** [raingart/Nova-YouTube-extension#14]
I like this script to much thanks for making it .
If you could add these fetures it would be awesome it can become one hub for better youtube experience.

1.Description button at the previous place.
(https://greasyfork.org/en/scripts/440613-youtube-proper-description)
2.Hide youtube A. notification icon B. Hide Shorts Tab c. Hide Explore, Trending or any feature you can take from this extension 
(https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid)
3.Watch letter button  Near the like button 

Thanks

**Comment by raingart** [comment]
1. I analyzed this script a few months ago and the principle of its operation is very simple. Youtube has essentially hidden the jet version of the Description section. But disabled js event.
And this script hides the new version, shows the old one, and adds a collapse function - it's all.
I don't know how long the old version will be available on the page. But as soon as it is finally removed, this whole script will break completely. I don't want to try to recreate the Description section.
I can advise you to try the "Description section in popup" plugin.

2. The extension is interesting as well as its implementation. I did not want to add the ability to block parts of the interface earlier. Since this can be done easily and simply through uBlock/AdBlock. And my implementation of this has greatly increased the number of plugins There are already quite a lot of plugins and they are poorly structured.
But I liked how the extension provided by you is implemented. I will test the possibility of creating a single plugin for scripting page elements. And maybe combine it with the existing ones

3. This can be easily implemented

**Comment by raingart** [comment]
I added "Watch letter button" in "Custom player buttons" 
try it [v 0.32.6](https://openuserjs.org/scripts/raingart/Nova_YouTube)

the rest is not completed. I'm not in the mood. Maybe when I get better I'll add.

**Comment by lxqz** [comment]
@raingart After looking through the plugins tab I was going to suggest adding an ability to change the YouTube logo to go to Subscriptions. Then I saw in the wiki that you already did it. Is it just me or is this not working for others too? I just see the two other options like this: 
![CleanShot 2022-08-17 at 13 02 29@2x](https://user-images.githubusercontent.com/49686156/185199898-fbeb8c8a-b670-4287-ad2f-763f1247718f.png)

**Comment by raingart** [comment]
@lxqz 
For a long time there was a plugin for a replacement logo-link to custom. But was removed. seemed unneeded to me

those two plugins above in the screenshot are not directly related to the logo

1st does it already. The block itself, due to the reduction of indents

2nd pagin this same top-block (search-div), when scrolling, is no longer fixed at the top of the screen. It seems to me that this makes sense for example - laptops with a small screen diagonal. Where there is a shortage of vertical space

Perhaps it is worth making an analytics module in the future. What would pass user settings for analytics. To find out which  plugins are requested and which no one uses. But too lazy to implement it. It's easier to remove something. And if no one complains with cries, then everyone is satisfied.

**Comment by raingart** [comment]
@lxqz 
For a long time there was a plugin for a replacement logo-link to custom. But was removed. seemed unneeded to me

those two plugins above in the screenshot are not directly related to the logo

1st does it already. The block itself, due to the reduction of indents

2nd pagin this same top-block (search-div), when scrolling, is no longer fixed at the top of the screen. It seems to me that this makes sense for example - laptops with a small screen diagonal. Where there is a shortage of vertical space

Perhaps it is worth making an analytics module in the future. What would pass user settings for analytics. To find out which  plugins are requested and which no one uses. But too lazy to implement it. It's easier to remove something. And if no one complains with cries, then everyone is satisfied.

**Comment by raingart** [comment]
Most likely, I will not implement blocking of individual page elements.
For this, there is uBlock Origin and any other ad blocker.
Almost any element can be blocked without knowing html/css with the eyedropper tool.

![Screenshot from 2022-08-17 20-20-47](https://user-images.githubusercontent.com/13064767/185203288-830b0432-e4da-4ee0-94ed-66fb929bf12f.png)

The extension you suggested is really well implemented. And you can dynamically see what was hidden.

My implementation will be a copy but without dynamic update. He blows no faster, no better. Absolutely no perks. Not worse with the extension, let alone adBlock.

After hiding the dislikes, the entire block with buttons became unnecessary for me and I hid it a long time ago
`www.youtube.com###top-row #actions`

The same goes for that sidebar.
`##ytd-mini-guide-renderer`

home, short, explorer - links to sorted shit. I don’t use them at all and they don’t understand those who click on them. One person complained that some of the plugins didn't work on the "Trending" page. Of course it doesn’t work, I don’t climb this garbage dump and I didn’t even wash it there to test something.

**Comment by raingart** [comment]
In fact, I refused 2 of the 3 functions you requested. 
Sincerely sorry. 
Just by implementing them, I, as it were, undertake to accompany them. Because I definitely won't be using them. There is no desire to waste time. With great alternatives. Which are more autonomous and unbreakable.

You and [1 other person](https://greasyfork.org/en/scripts/433360-nova-youtube/discussions/142501) really suggested new ideas for implementation. I appreciate it. 
But in my opinion, implementing them is the wrong approach.
The solution is already there. And my possible implementation of them is not a solution to the essence of the problem, but simply its concealment.

The 2nd part of the requests is something that goes beyond the scope of the script
for example; https://greasyfork.org/en/scripts/1590-no-embed-youtube

or something that is quite difficult to implement and few people need:
https://greasyfork.org/en/scripts/412659-youtube-playlist-duration-sort
https://greasyfork.org/en/scripts/447447-youtube-audio-mode

**Comment by lxqz** [comment]
@raingart Analytics is a neat idea, but yeah I imagine it's more work than it is worth, especially for a free tool! 

As for the replacement link, in case you're curious why someone would need it, I think many who use it do it because the YouTube home page can be distracting when trying to focus. People often click the logo after finishing a video and the home page specializes in putting particular videos in front of you that you are most likely to click on, so jumping somewhere else (like subscriptions) is a small, but often effective way to prevent distractions and remind oneself to get back on track. 

It's no big deal though as there are other scripts on greasyfork that do it. I was just curious if the issue was just me since I saw it listed in the wiki. Thanks for the tool anyway. So many awesome plugins in there!

**Comment by raingart** [comment]
@lxqz  restored the plugin "YouTube logo"
update to [0.32.9](https://openuserjs.org/scripts/raingart/Nova_YouTube)

p.s. I personally use browser bookmarks bar
