### ISSUE TITLE
[Bug] Theatre mode stopped working

### ISSUE THREAD

**Issue by caniyo** [raingart/Nova-YouTube-extension#141]
First of all thank you for this absolutely amazing script. I really appreciate all the time and passion you invest in this project!

That being said, since a few days ago the theatre mode option stopped working. So when I watch a video the player doesn't get resized accordingly and just stays small. I guess Google have changed some code again.

 - Browser: Firefox 121.0.1 
 - Violentmonkey 2.17.0
 - Nova 0.46.1

**Comment by raingart** [comment]
About a month ago they changed the API. I looked in other scripts, no one used api-call. Everyone was emulating a button press.
I had to dig through the youtube libraries and I found a new name for a call-fn. And this challenge did not always work. Ok, let's take it as it is.

And this new call worked for less than a month. As you noticed, it stopped working again. It is in the code "works" but only with a specific launch flag.
![Screenshot_2](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/cecf002a-caa8-42d5-9f96-99987d577b1e)

Today I was looking for new API requests again. But I couldn’t find a way to launch them. I gave up and did “like everyone else” - also through emulation

I want to do everything “right”. There is an API call - use it. But everything works out through the ass. And have to use all sorts of crutches that don’t understand how they work and always break.

p.s. Thank you for your gratitude. Because more and more often I wonder - what the hell am I doing? I’m trying to “fix” or “improve” the product of a “small and poor” corporation using workarounds, using non-standard means. After all, it’s so difficult to add settings yourself or at least the possibility of integration. After all, they do not have the opportunity and resources. And I, like a child, “digging with a stick in an anthill”.
