### ISSUE TITLE
Videos Sometimes Don't Start

### ISSUE THREAD

**Issue by poopydangle** [raingart/Nova-YouTube-extension#15]
For some reason when I open a video sometimes it will cause the video to not start and the total time for the video flashes from 0:00 and the actual time.

Using Tampermonkey on Chrome with script version 0.32.9.

**Comment by poopydangle** [comment]
It seems that the option "Pin player while scrolling" is what is causing this.

**Comment by raingart** [comment]
not enough data to find out the cause of the error. 
If the error appears regularly, then make a video. And a message from the browser console. 

Theoretically, the plugin "Pin player" should not interfere with the work of the player.

**Comment by raingart** [comment]
Try disabling Nova. Perhaps a problem with the GPU or the browser.

**Comment by raingart** [comment]
too many errors.
Judging by the video, it has a blocking connection to receive data about the video file.
Try disabling VPN/Proxy or ad blocker.

Try honeydew busting.
1 Disable ALL scripts/extensions
2. Leave only Nova
3. Enable 1 extension/scripts and check

or just uninstall Nova.

**Comment by raingart** [comment]
Probably the problem is in conflict with another extension.
in order for me to solve the problem, you need to give me your folder (`C:\Users\<username>\AppData\Local\Google\Chrome\User Data\Default`) from the browser user
**But this is a direct threat and compromise of your data.**

or You can pass a complete list of all script extensions so that I can personally check.

If you yourself fail to find out what the problem is. The method of enumeration and disconnection of all scripts.
I recommend that you use another similar extension. It has a different implementation and I suppose there should be no gaps
https://chrome.google.com/webstore/detail/improve-youtube-video-you/bnomihfieiccainjcjblhegjgglakjdd

**Comment by poopydangle** [comment]
I believe I can close this issue, I disabled one of my other extensions and it doesn't seem to happen anymore.

**Comment by raingart** [comment]
@poopydangle I'm glad you managed to fix the bug. You can specify what extension it was? I'll see what the problem is

**Comment by poopydangle** [comment]
I believe the problem was with an extension called "Auto Quality for YouTube"

**Comment by poopydangle** [comment]
I believe the problem was with an extension called "Auto Quality for YouTube"
