### ISSUE TITLE
[Bug] volume hotkey wheel save

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#156]
The "Volume" setting in the PLAYER section is toggling my volume hotkey to "wheel" when I keep setting it to "none". Also, the default hotkey step is 10, which is silly because the default should be not changing it at all (YT's default is 5%).

 - Browser: Firefox 122.0.1
 - Violentmonkey 2.18.0
 - Nova 0.47.0

**Comment by raingart** [comment]
error in configuration parameters. After updating added support keyboard other than Latin (English)

find the line `volume_hotkey: {`

after replace 
```
{ label: 'none' },
```
to
```
{ label: 'none', value: false },
```

if there is no value in a parameter should be ignored when saving. To reduce the data stored size. But the absence of value causes many triggers to fail. Correctly replace everything without value with false. But I don’t like it when the user changes a couple of parameters and all the other inactive ones are entered into the database.

**Comment by raingart** [comment]
![Screenshot_1](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/2e5f732e-bab2-4ece-9625-e61ddac17b0a)

**Comment by raingart** [comment]
why 10 was chosen instead of 5 - three reasons:
1. This is a clear indication that the standard function has been successfully replaced.
2. 10 steps sampling is enough for me. Since different videos have different volumes, the 5% accuracy is unnoticeable. I don't hear a difference of 50-55% or 95-100%. Locally in the system I can hear a difference of 2%, but not on YouTube.
3. you need a number that is a multiple of 100. five are already taken and ten is the next closest

Essentially the reasons are technical

**Comment by zkisaboss** [comment]
Thanks, this appears to have fixed the issue for me.
