### ISSUE TITLE
[Feature] Plugin to set chat to "Live chat" automatically

### ISSUE THREAD

**Issue by pointydev** [raingart/Nova-YouTube-extension#161]
A plugin that could set livestream chats to "Live chat" mode instead of "Top chat" automatically would be really useful in smaller streams in order to prevent messages in low traffic chats from being missed.

Thanks,
pointy

**Comment by pointydev** [comment]
While your AI response seems to have got a little confused in what I was requesting, it did link to [HyperChat](https://chromewebstore.google.com/detail/naipgebhooiiccifflecbffmnjbabdbh), which does have this feature after looking at their source:
https://github.com/LiveTL/HyperChat/blob/4dcfed28c36da9226feb0687a79f43edadc291fe/src/scripts/chat-injector.ts#L153-L161

**Comment by raingart** [comment]
it turned out to be easy

add a new plugin after the line `window.nova_plugins = [];`
```
window.nova_plugins.push({
  id: 'livechat-toggle-mode',
  title: '"Live chat" mode instead of "Top chat"',
  run_on_pages: 'live_chat, -mobile',
  //restart_on_location_change: true,
  section: 'sidebar',
  _runtime: user_settings => {
        NOVA.waitSelector('#chat-messages #menu a:nth-child(2)[aria-selected="false"]'/*, { destroy_after_page_leaving: true }*/)
               .then(btn => btn.click);
  },
});
```

and replace the iframe launch limiter
this code 
`!location.pathname.startsWith('/embed')`
to 
`(!location.pathname.startsWith('/embed') && !location.pathname.startsWith('/live_chat'))`

**Comment by pointydev** [comment]
With these modifications, it doesn't appear to be working:
![](https://the.yog.zone/3ffXL5P.png)
![](https://the.yog.zone/446mC5Z.png)

I have it enabled in settings:
![](https://the.yog.zone/3VmomEF.png)

And here are all the references to Nova in console:
![](https://the.yog.zone/7UtPL5i.png)

Currently, I don't have time to do localisation, but I'll considering doing so in the future.

**Comment by raingart** [comment]
crap I don't see any other way except to add a delay so that the default yt event listener connects

replace
`.then(btn => btn.click);`
to
```
    .then(async btn => {
          await NOVA.delay(500);
          btn.click();
        });
```

**Comment by pointydev** [comment]
It seems to be working just when running asynchronously, without using delay:
```js
.then(async btn => {
      await btn.click();
    });
```

**Comment by raingart** [comment]
I think this is a bug and not a feature
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

I wonder what will happen in other browsers.
I didn’t realize that click was asynchronous. Perhaps asynchronous calls have some lag which is enough to use event listener callback

For example, it was a surprise to me that this code works
`Promise.resolve(document.querySelector(selector);`
but it turned out that he would never return the element.

**Comment by pointydev** [comment]
> I wonder what will happen in other browsers.

For the record, I'm using Chrome Dev `124.0.6315.2`.

**Comment by pointydev** [comment]
I'm likely moving to Firefox when Manifest V2 gets disabled later this year in Chromium, and I don't really feel like doing any workarounds to keep it, but thanks for the custom build suggestions. If you'd like to continue the conversation, I'm `@pointy` on Discord.

**Comment by raingart** [comment]
oh shit, it's broken

[example video](https://www.youtube.com/watch?v=yK4mTN3B1d8)
does not work - `#chat-messages #menu a:last-child[aria-selected="false"]`
works correct - `#chat-messages #menu a[aria-selected="false"]`

ps about `await btn.click();`
yes this is a bug. await adds ~500ms latency.
For example [here](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/player/quality.js#L225-L227) the script does not work because the delay is already 1500ms needed
