### ISSUE TITLE
[Bug] Userscript not working with Edge

### ISSUE THREAD

**Issue by Oreloth** [raingart/Nova-YouTube-extension#194]
*Describe what exactly the error is. So that I don't interrogate you*
*make sure the error is not related to others extensions/script related to YT*

Userscript seems to not launch with Microsoft Edge, only have a few tips, so this is what I have:

 - Browser: Microsoft Edge 129.0.2792.79 
 - Tampermonkey 5.1.1 
 - Nova 0.50.0.1+7950172 

Logs: 
```javascript
This document requires 'TrustedHTML' assignment.
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12471  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12471
Promise.then
insertSettingButton @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12463
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12246
wt @ VM5082:9
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1
window.__f__m20eermx.u3 @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1
wt @ VM5082:9
o.setMessageListener.o @ VM5082:80
(anonymes) @ VM5082:81
set @ VM5082:89
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1
Wo @ VM5080 content.js:56
Ho @ VM5080 content.js:57
(anonymes) @ VM5080 content.js:54
(anonymes) @ VM5080 content.js:69
yt @ VM5080 content.js:8
t @ VM5080 content.js:9
_ @ VM5080 content.js:69
wt @ VM5082:9
f @ VM5082:76
l @ VM5082:78
(anonymes) @ VM5082:78
Wn @ VM5082:17
send @ VM5082:78
(anonymes) @ VM5082:81
v @ VM5082:77
yt @ VM5080 content.js:8
f @ VM5080 content.js:68
d @ VM5080 content.js:71
(anonymes) @ VM5080 content.js:71
wn @ VM5080 content.js:14
send @ VM5080 content.js:70
w @ VM5080 content.js:54
No @ VM5080 content.js:56
(anonymes) @ VM5080 content.js:55
yt @ VM5080 content.js:8
t @ VM5080 content.js:9
Xo @ VM5080 content.js:51
Zo @ VM5080 content.js:64
(anonymes) @ VM5080 content.js:63
(anonymes) @ VM5080 content.js:14
yt @ VM5080 content.js:8
t @ VM5080 content.js:9
(anonymes) @ VM5080 content.js:14
(anonymes) @ VM5080 content.js:59
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1021
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:3357  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:3357
runOnPageLoad @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:5317
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:3354
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:3343
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1860
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1021
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1860
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1029
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1021
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889  This document requires 'TrustedHTML' assignment.
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1889
Promise.then
_runtime @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:1860
(anonymes) @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12143
run @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12118
appRun @ userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:12329
userscript.html?name=Nova-YouTube.user.js&id=5a871e1a-7831-494e-b885-9b41c6af0a23:4241  This document requires 'TrustedHTML' assignment.
```

Asked to Copilot, since Edge is from the same company, and this is what I got:

> 1. Extensions Disabled: Ensure that the extension allowing Userscripts (like Tampermonkey or Violentmonkey) is installed and enabled.
> 2. Security Settings: Edge might block certain scripts for security reasons. Check the security and privacy settings in edge://settings/privacy.
> 3. Browser Updates: Sometimes, a browser update can cause incompatibilities. Make sure your browser and extensions are up to date.
> 4. Conflicts with Other Extensions: Other extensions might interfere with the Userscripts. Try temporarily disabling other extensions to see if the issue persists.
> 5. Script Issues: The script itself might contain errors or be incompatible with the current version of Edge.

Some searches are pointing to a "cross-origin" problem, so I also tried to find a clue in the experimental settings page (edge://flags) but found nothing, maybe you will.

**Comment by Oreloth** [comment]
Tested with Violentmonkey 2.26.0, same problem.

By the way, it works with:

Opera GX LVL6 (core: 113.0.5230.135)
Tampermonkey 5.1.6194 (Last Opera version)

**Comment by raingart** [comment]
Ce problème est observé dans les forks primaires de Chromium.

Ici, je décrivais un peu le problème #182

Je travaille sur une nouvelle version, mais le processus est très lent. J'espérais auditer de nombreux logiciels locaux LLM, mais j'ai été très déçu par leur performance. Ils sont bien adaptés pour les données encyclopédiques et une version plus confortable d'un équivalent de Stack Overflow, mais en tant qu'assistant, ils laissent à désirer. Il m'a fallu plusieurs semaines après avoir refait certaines parties pour identifier des erreurs logiques complexes. Bien que les solutions proposées soient extrêmement intéressantes, leur mise en œuvre a été compliquée.

De plus, il m'a pris beaucoup de temps à tenter d'implémenter shadows-DOM pour bloquer les changements potentiels venant de YouTube ou d'autres scripts et améliorer l'isolement. Cependant, je suis insatisfait des résultats obtenus et envisage probablement de rejeter cette méthode. Je vous encourage à examiner d'autres projets similaires. Peut-être leur progression est plus significative. Et contrairement à moi, ils n'ont pas connu de ralentissement pendant six mois.

**Comment by Oreloth** [comment]
I'm sorry to tell you that but... I never found a better script than yours for enhancing YouTube.

**Comment by raingart** [comment]
Hi check the [beta](https://gist.github.com/raingart/d734dd35f7090e9824df15f52c36f8a0) vers

**Comment by Oreloth** [comment]
I was working on a script to add most of your functions to the custom script section of "Enhancer for YouTube" for a personnal purpose.

Everything seems to work perfectly with your new update, thank you very much for you hard work, sir.

**Comment by raingart** [comment]
Feel free to ask any questions about functionality, and I'll do my best to help.

Initially, I wanted to maximally distance myself from the YouTube API call and use HTML5, as I remembered how the transition to Polymer broke almost all existing scripts. But in the end, I couldn't resist the much simpler solution of using their API.

Here are some of the YouTube API calls that are quite useful:
```
movie_player.getPlayerResponse();
movie_player.getVideoData();
document.body.querySelector('yt-playlist-manager').getPlaylistData();
document.addEventListener('yt-action', function (evt) {
```

I also used this method:
```
NOVA.waitSelector('video')
         .then(video => {
            video.addEventListener('loadeddata', () => console.log('loadeddata'));
            video.addEventListener('canplay', () => console.log('canplay'));
            video.addEventListener('play', () => console.log('play'));
            video.addEventListener('playing', () => console.log('playing'));
         }); 
```
The main thing is to make it so that you can figure it out on your own over time. For example, YouTube Center was so monolithic that even its author wasn't able to rework it. Therefore, I chose the most flexible system up to which point I managed. I don't know how it helped others. I hope at least something is clear to you. And, as you noticed, I'm a fan of a lot of commented (deactivated) code. Who knows when it might come in handy?

**Comment by Oreloth** [comment]
Yes, and your comments were really helpful to include some functions to my "Enhancer for YouTube" while waiting for your update.

I recently noticed dislikes count from your beta is not working anymore. But simply installing "Return YouTube Dislike" solves it.

Can I suggest you to move the control panel to be compatible with "Enhancer for YouTube" since it has some useful functions your script does not have?

![image](https://github.com/user-attachments/assets/61c38388-a619-451f-a801-1b69662aa4d1)

As you can see, your control panel should be better just above the video title I think, before the "#title h1" with this kind of code from line 8287:

```js
window.nova_plugins.push({
  id: 'player-control-below',
  title: 'Control panel below the player',
  'title:pl': 'Panel sterowania pod odtwarzaczem',
  run_on_pages: 'watch, -mobile',
  section: 'player-control',
  _runtime: user_settings => {
    NOVA.waitSelector('.ytp-chrome-bottom, #title')
    .then(async ([control_panel, titleDiv]) => {
      if (control_panel && titleDiv) {
        const height = NOVA.css.get(control_panel, 'height') || '40px';
        
        NOVA.css.push(`
          #movie_player {
            overflow: visible;
          }
          .ytp-chrome-bottom {
            position: relative;
            transform: translateY(100%);
          }
          #title {
            margin-top: ${height};
          }
        `);
        control_panel.parentNode.insertBefore(control_panel, titleDiv);
      }
    });
  }
});
```

Since it is in conflict with "Enhancer for YouTube" toolbar while place "under" the player and there is not enough room if you enable most of functions and set the control panel inside the player. I assume it will be easy for you since you already have some statistics added in the div containing the title.

I'll try to adapt the code myself to suggest this modification but I'm not really used to JS and your script is really big, so it will probably take some time.

**Comment by raingart** [comment]
Of course, I'll look into improving compatibility. It's obvious that some things will be in conflict. But thanks to the modular structure, users can choose to enable or disable certain features (it's clear that using such scripts might cause problems, for example, hotkey interception).

There's a possibility for external scripts to get information about certain Nova plugins:
```window.nova_settings```
The issue is that I frequently change the names of these plugins. I was asked to add attributes to the ```<html>``` tag that would show active settings, an interesting proposal, but I was too lazy to implement it. However, it would dynamically allow for the cancellation of some CSS adjustments and would indeed help with compatibility for scripts that rely on CSS.

I also refused to create an extension version because Nova turned out to be quite popular, and there were people who criticized me and behaved aggressively, demanding things. Such hostility that I decided that I shouldn't. I also rejected the transition to MV3, despite almost everything being ready for it.

I also found compatibility issues with some parameters of the "Auto wide player (Theater mode) > Mode."

Interestingly, on my Windows OS, I use an outdated version of Chromium (chrlauncher) that is not compatible with the minimum version available in the store. Of course, that's my problem, and I'm too lazy to update my browser. It's just curious why 128 is the minimum version. I installed it through Dev mode without noticing any errors.

![Screenshot_4](https://github.com/user-attachments/assets/14207701-e293-486c-9fa7-99fdc69efe8c)

I really liked two things in Nova: the module for translation within the extension itself and the dynamic example of dimming.

![Screenshot_1](https://github.com/user-attachments/assets/39645f19-e7ea-4030-869e-180524078d95)

The architecture of Nova cannot be applied dynamically to settings. Partially, CSS could have been implemented, but never mind.

By the way, there's a cool extension where a guy achieved full instant synchronization of settings: https://github.com/YouTube-Enhancer/extension/tree/dev

I once created a Google Sheets table where anyone could add translations for their language. I protected some columns. But after people started insulting and spamming, I disabled it. In essence, users only translated about 1.5 languages, but I left only Polish. I resorted to machine translation for the rest, but then people complained that it was terrible, and I came to the single correct solution - if you don't know English, that's your problem.

By the way, is there a recommended way for Nova to determine if the "Enhancer for YouTube" extension has been initialized? I just noticed that there's a class in ```<html>```: ```efyt-control-bar-visible efyt-control-bar-position-absolute```

For example, some of its settings obviously would cause a conflict. For instance, your implementation of "Mini player" and my "Pin player." Of course, in most cases, no one would apply both, but it was funny when this script (https://greasyfork.org/en/scripts/10523-youtube-always-theater-mode) failed after YouTube changed its template, and another user tried to activate my implementation, causing everything to break because we both relied on the same player container names.

**Comment by raingart** [comment]
I definitely didn’t understand, but I guess this dissatisfied user reported that there is a conflict with another [extension](https://chromewebstore.google.com/detail/youtube-windowed-fullscre/gkkmiofalnjagdcjheckamobghglpdpm)

By the way, your users seem to be quite non-aggressive, at least no one is going to kill or steal your dog. Yes, and there are no those who complain that they do not work on Windows 98 in the old version of ~~internet explorer~~ edge

![Screenshot_3](https://github.com/user-attachments/assets/d95e1a5b-2ab7-4b6c-b53e-7a64927bf237)

**Comment by Oreloth** [comment]
I don't even see why using an extension just to make the video player fitting the browser tab. Just use fullscreen to do it...

By the way, about translations, if you want, I can provide you native quality french one for your extension.

**Comment by Oreloth** [comment]
To simplify translation, I made a Python script to extract all line containing `'title:pl':` and their respective line number to find em quickly in the original file. Here is the script:
```py
import os

def extract_and_write_lines(input_filename):
    # EN: Get the file extension
    # FR: Obtenir l'extension du fichier
    _, extension = os.path.splitext(input_filename)
    output_filename = f"output{extension}"

    try:
        with open(input_filename, 'r', encoding='utf-8') as input_file, \
             open(output_filename, 'w', encoding='utf-8') as output_file:
            for line_number, line in enumerate(input_file, start=1):
                if line.strip().startswith("'title:pl':"):
                    formatted_line = f"{line_number}: {line.strip()}\n"
                    output_file.write(formatted_line)
                    # EN: Also display in console
                    # FR: Afficher dans le terminal
                    print(formatted_line, end='')
        print(f"Extracted lines have been written to {output_filename}")
    except IOError as e:
        print(f"An error occurred: {e}")

### EN: Usage of the function
### FR: Utilisation de la fonction

# EN: Replace with your filename
# FR: Remplacez par votre fichier
filename = "nova-dev.user.js"
extract_and_write_lines(filename)
```

Now I'm working on a (clean) french translation for your script.

**Comment by raingart** [comment]
>I don't even see why using an extension just to make the video player fitting the browser tab. Just use fullscreen to do it...

I didn’t understand this either until I got an ultra-wide monitor. It's all about the vertical screen fill

![Screenshot_6](https://github.com/user-attachments/assets/35623c01-b2f5-4bff-8cff-c885e5fdf54e)
![Screenshot_7](https://github.com/user-attachments/assets/04e2f09a-beaf-495b-b548-37d83905cbfb)

>I can provide you native quality french one for your extension.

This would be good, but localization is divided into many plugins. And it will be quite tedious. Although if you look at the statistics, there really are a lot of Polish users. Estimate how many users are from France, besides you there is one more person.

upd: it’s cool that you thought of making a script. I thought of another way. This is to add a tag to all elements https://developer.mozilla.org/ru/docs/Web/HTML/Global_attributes/contenteditable and simply edit the labels on the page. And then save the html.

I'll give you two more cool scripts that I really like
https://greasyfork.org/en/scripts/389174-yt-peek-a-pic
https://greasyfork.org/en/scripts/370755-youtube-peek-preview

**Comment by raingart** [comment]
and also a couple of small scripts that I use almost every day. for me they are very comfortable

https://openuserjs.org/scripts/raingart/Hotkeys_Page_Scroll
https://openuserjs.org/scripts/raingart/Add_YouTube_link_to_Google_search

**Comment by raingart** [comment]
forgot to add a screenshot of analytics for Nova for 3 last months

![Screenshot_5](https://github.com/user-attachments/assets/74b45ea5-8e55-4152-b521-a45c724da59f)

**Comment by Oreloth** [comment]
First, yes I have a "backup" in my mails. ;)

Then, this is the first iteration of my translation for your script, it may not be perfect since I don't have context for every single label, but it's 90 % accurate. I recommend you to test to check if I not broke anything.

https://gist.github.com/Oreloth/78d129d71ed21bde72685b160ab54312

For your links, many things to say:
* YouTube links to Google is a good idea, but I don't use Google search engine since many years.
* contenteditable attribute is not a good idea, but I don't see how to make it efficient to translate your script, it will require to change all your structure, which is really tedious.
* The userscripts can be useful, especially for thumbnails since I extract often them. That's one of the reasons I like Nova, it allows me to easily extract thumbnails and take live screenshots.

**Comment by raingart** [comment]
Yes, Google has deteriorated greatly over the past decade. It's hard to find anything in it. I use if need information/answer
https://www.perplexity.ai/
https://www.morphic.sh/

but alas, it’s still easier to find which website with it

**Comment by Oreloth** [comment]
Yes, I use Perplexity since their very first closed beta, it was already really promising at the beginning, this AI is really helpful. Did not know about Morphic, I'll stress test this one soon to see what it can handle.

**Comment by raingart** [comment]
Thank you! the most important things have been translated, I think I’ll translate the rest myself
It turned out that the translation module was not working properly
Also demo mode does not work which should display all available settings

![Screenshot_9](https://github.com/user-attachments/assets/8f1004fd-1bfb-48a4-8299-d81ff3c8f7f4)

It turns out that the Polish translation is far from complete. By the way, if you are interested, this is approximately how the demo mode should work - show all the settings that are available. There are many more of them, just many hidden through conflicts and dependencies

[R.zip](https://github.com/user-attachments/files/18086330/R.zip)

I hope that all two users from France will find this useful. Although many people use ublock because there are probably 2 times more users (as many as 4-5!)

Btw, did you know that iridium also partially woke up from stasis? The interesting thing is that he chose a completely different way to modify the json-skeleton that is passed to the template

https://github.com/ParticleCore/Iridium

By the way, I tried to use shadowDOM to isolate the influence of external scripts and Youtube itself, but alas it turned out to be difficult. But the idea itself is quite interesting. And maybe you should take a closer look at it. This increases security and stability by an order of magnitude

I personally once really liked the architecture of another [script](https://github.com/Taraflex/ranobe-ebook-loader/tree/master/src)
I wanted to use svelte.dev and after preact.js They are so cool. But it was already difficult to integrate them. But for new projects they can be useful

I hope that at least some of the information I gave was interesting. And not at the level of chatty chaGPT.
I repeat, if you need help or information on how something from Nova works or how something can be done, I will try to help and show you what I know myself.

Good night!

**Comment by Oreloth** [comment]
Oh, interesting, I came here from Iridium first, but it was dead, then I found Nova, that was very similar to Iridium, even better in my opinion. I'll check that.

**Comment by raingart** [comment]
It was a bit complicated, but it seems to have worked out (control-panel-under conflict).

The problem was numerous, but the main issue was that Nova initializes before 'Enhancer for YouTube', and the parameters are taken from constants. This means that if you ever change them, everything will break. I failed to extract all the necessary 'fundamental' variables, some things are 'relative'

https://gist.github.com/raingart/2cd299b8d9d96a61aaa23aba5a4889fe

In case you want to go deeper and maybe find a better solution
current general code part of the plugin:
```
NOVA.waitSelector('.ytp-chrome-bottom')
         .then(async control_panel => {

            // const { height } = window.getComputedStyle(control_panel); // can't rename a variable
            if ((heightPanel = NOVA.css.get(control_panel, 'height'))
               && (heightProgressBar = NOVA.css.get('.ytp-progress-bar-container', 'height'))
            ) {
               const SELECTOR_CONTAINER = '#page-manager .ytd-page-manager:not([fullscreen])';
               const height = `calc(${heightPanel} + ${heightProgressBar})` || '51px';
               let offset = '100%';

               // fix conflict with "Enhancer for YouTube™" (https://github.com/raingart/Nova-YouTube-extension/issues/194#issuecomment-2531465170)
               if (document.documentElement.classList.contains('efyt-control-bar-visible')) {
                  const efytHeight = NOVA.css.get('.efyt-control-bar', 'height') || '36px';
                  const efytTop = NOVA.css.get('.efyt-control-bar-position-absolute', 'padding-top') || '45px';
                  offset = `calc(${offset} + max(${height}, ${efytHeight}, ${efytTop}))`;

                  NOVA.css.push(
                     `/* fix efyt offset (description, sidebar) */
                     ${SELECTOR_CONTAINER}:not([theater]) #above-the-fold {
                        margin-top: calc(${efytTop} - ${efytHeight}) !important;
                     }
                     /* fix efyt control-tooltip */
                     ${SELECTOR_CONTAINER} .ytp-tooltip,
                     ${SELECTOR_CONTAINER} .ytp-settings-menu {
                        transform: translateY(calc(${height} + max(${height}, ${efytHeight}, ${efytTop}))) !important;
                     }`);
               }

               // fix for [theater-mode] plugin
               // if (user_settings.player_full_viewport_mode) {
               //    const CLASS_OVER_PAUSED = 'nova-player-fullviewport';
               //    SELECTOR_CONTAINER += ` #movie_player:not(${CLASS_OVER_PAUSED})`;
               // }

               // fix conflict with plugin [theater-mode]
               if (['force', 'offset'].includes(user_settings.player_full_viewport_mode)) {
                  SELECTOR_CONTAINER += `:not([theater])`;
               }

               NOVA.css.push(
                  `${SELECTOR_CONTAINER} {
                     --nova-control-bar-offset: ${offset};
                     --nova-control-bar-height: ${height};
                  }

                  /* convert control-gradient to background control */
                  ${SELECTOR_CONTAINER} .ytp-gradient-bottom {
                     display: block !important;
                     height: ${heightPanel} !important;
                     padding: 0;
                     background-color: #0f0f0f; /*--yt-spec-text-primary-inverse*/
                  }

                  /* control move below */
                  ${SELECTOR_CONTAINER} .ytp-gradient-bottom,
                  ${SELECTOR_CONTAINER} .ytp-chrome-bottom {
                     transform: translateY(var(--nova-control-bar-offset));
                     opacity: 1 !important;
                  }

                  /* fix description, sidebar(on theater) */
                  ${SELECTOR_CONTAINER}:not([theater]) #below,
                  ${SELECTOR_CONTAINER}[theater] > #columns {
                     margin-top: var(--nova-control-bar-height) !important;
                  }

                  /* fix control (overflow-x) */
                  ${SELECTOR_CONTAINER} #movie_player {
                     overflow: visible;
                  }

                  /* fix captions */
                  ${SELECTOR_CONTAINER} .caption-window {
                     margin-bottom: 0;
                  }

                  /* fix channel avatar (embed: bottom-right corner) */
                  ${SELECTOR_CONTAINER} .ytp-player-content.ytp-iv-player-content {
                     bottom: ${NOVA.css.get('.ytp-player-content.ytp-iv-player-content', 'left') || '12px'};
                  }

                  /* fix control: tooltip, timeline-preview */
                  ${SELECTOR_CONTAINER} .ytp-tooltip,
                  ${SELECTOR_CONTAINER} .ytp-settings-menu {
                     transform: translateY(var(--nova-control-bar-height));
                  }

                  /* fix for rounded player (without login) */
                  #ytd-player {
                     overflow: visible !important;
                  }`);
```

**Comment by raingart** [comment]
[nova-extensions_v1.50.0.zip](https://github.com/user-attachments/files/18167672/nova-extensions_v1.50.0.zip) is the extension ver, maybe it's easier for you to test this way
