### ISSUE TITLE
[Bug] Failed with importing setting

### ISSUE THREAD

**Issue by Pi3truch** [raingart/Nova-YouTube-extension#195]
- Browser: Opera One: 114.0.5282.185, Chromum:128.0.6613.186
 - ...monkey 2.29.0
 - Nova 0.50.0

I struggled with this error:
`TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.`

dev ver:
https://gist.github.com/raingart/d734dd35f7090e9824df15f52c36f8a0

works fine, for now*.

But I cannot import the setting from the previous version.
I get the message it is imported but all the switches are turned off.

*I will see when I turn on ale the settings.

I hope there is a way to import the settings. I have it quite a lot so it is a hassle to do it manually.

**Comment by raingart** [comment]
in the new version the [url](https://raingart.github.io/nova/) of the settings page has changed
the old and new settings pages are incompatible because they use a different method for synchronizing settings

**Comment by raingart** [comment]
if you use violentmonkey you can directly modify the settings

![Screenshot from 2024-12-06 19-16-10](https://github.com/user-attachments/assets/9c42e5a8-884a-4fd0-a05c-1f59baa0dc42)

If you don’t have access, you can directly upload/download settings through the browser console

![Screenshot from 2024-12-06 19-20-34](https://github.com/user-attachments/assets/dd411678-849a-4139-9b71-91b0404735d5)


`Storage.getParams(i=>console.log(i))`

```
Storage.setParams({
    ...
})
```

**Comment by Pi3truch** [comment]
I used violentmonkey method.
Working great. Thanks a lot!

**Comment by raingart** [comment]
Great, 
it’s just a pity that the author of Violentmonkey won’t be able to port it to Manifest v3 and if I use another Monkey, then perhaps only the 2nd method will remain

Btw did you know that you can directly install scripts in the browser. But alas, this does not work with Nova because with this method there is no access to storage and GM_ calls


https://github.com/user-attachments/assets/f800f335-f3b9-4b54-b405-11fd5ca3eb34
