### ISSUE TITLE
YouTube URLs being redirected

### ISSUE THREAD

**Issue by alkaris2** [raingart/Nova-YouTube-extension#23]
I don't know what's going on with this extension but for some reason when installed as GreaseMonkey script, its taking typical YouTube URLs and redirecting to some other site called `cinemaphile.com`  What is this and why are some YouTube videos being redirected to this site, and how do I turn it off from redirecting to this site? I don't know if this connected to either Theatre Mode or Video Unblocking, but this is super annoying it's redirecting away from YouTube like that where I can't just view the regular video page.

This happens to be on videos that have content warnings on them like 1 out of 4 videos will be redirected away from YouTube to this other site just to play the video. The videos with content warnings shouldn't be treated as blocked videos since YouTube still allows you to watch them once you've clicked the button acknowledging them.

**Comment by raingart** [comment]
disable the plugin "Try unblock if video not available in your country"

**Comment by raingart** [comment]
the essence of the plugin is that it redirects some video. Which probably (in your case, most likely erroneously) perceives as blocked for your region.
To another site (cinemaphile.com or hooktube.com) which is (probably) in a different region and you have the opportunity to view it

I can try to track down the cause of the failure if you specify the exact version of what and where and on what it is installed.
Because the webstore version of the extension is [abandoned](https://github.com/raingart/Nova-YouTube-extension/wiki/Stop-developing-NOVA-builds-as-extensions) and work in GreaseMonkey is not possible with the compatibility [check function](https://github.com/raingart/Nova-YouTube-extension/blob/master/UserScript/check-browser-support.js#L8)

**Comment by raingart** [comment]
send me a link to these videos so that I can improve the detection. 

And if there is an option how to name the plugin more concisely and more clearly, then tell me. Because it's obvious that if you couldn't find this plugin, then it's badly named.

**Comment by alkaris2** [comment]
I tried out disabling "Unblock video not available" and shows the video as normal without redirect.

as for the videos it happens to be these following videos here thats perceived as blocked even though it's not and just content warning by YouTube.
https://www.youtube.com/watch?v=ek7JK6pattE
https://www.youtube.com/watch?v=qAYlTiV-Zf8

Each have sensitive topics which YouTube presents to viewers if they're age restricted. Could create a check if the video is age-restricted and what topics it mentions and perhaps "whitelist" them so it doesn't get caught up as a blocked video.

also I meant to say Violentmonkey BETA, not Greasemonkey despite similar naming of the extension. I'm not even using the webstore extension at all.

**Comment by raingart** [comment]
try [Nova beta](https://openuserjs.org/scripts/raingart/Nova_YouTube) ver.
Instead of a direct redirect, there will be a request to open a popup.

region blocked videos:
- https://www.youtube.com/watch?v=bTm3kwroEyw - https://watannetwork.com/tools/blocked/#url=bTm3kwroEyw
- https://www.youtube.com/watch?v=3U2UGM0ldGg - https://watannetwork.com/tools/blocked/#url=3U2UGM0ldGg
- https://www.youtube.com/watch?v=OztVDJXEfpo - https://watannetwork.com/tools/blocked/#url=OztVDJXEfpo
