### ISSUE TITLE
[Feature Request] Direct-click "Save to playlist" button

### ISSUE THREAD

**Issue by Coldblackice** [raingart/Nova-YouTube-extension#32]
Youtube previously had the "Save to playlist" button directly accessible, however, they've recently buried it in a submenu now, requiring multiple clicks. 

Would it be possible to add the ability for this button to be made directly clickable? And perhaps also the option to hide/remove the "Clip" and "Thanks" buttons, which clutter up the interface.

**Comment by raingart** [comment]
The "Save to playlist" button and others appear with a large screen resolution.

![Screenshot from 2022-11-11 12-40-49](https://user-images.githubusercontent.com/13064767/201325077-f935dc37-8012-4a0e-b228-17e5a80fc1de.png)

Unfortunately, I don't know how to cheat youtube scripts to move buttons or change them to another screen size.

As for scripting various page elements, this is a great extension:
https://chrome.google.com/webstore/detail/khncfooichmfjbepaaaebmommgaepoid

I will try to find other scripts. And see how they work. Because at the moment I only have a stupid idea to just open the existing buttons and add my own. But it's a crutch

**Comment by raingart** [comment]
This [script](https://greasyfork.org/en/scripts/443136-youtube-compact-button-labels) (now non-working now) pushed me to one of the solutions

if you are satisfied with such a solutions, I will implement it

![Screenshot from 2022-11-14 14-46-39](https://user-images.githubusercontent.com/13064767/201666169-02cf9ccd-6e83-43d3-932b-a7a0e040e98f.png)

**Comment by raingart** [comment]
"Buttons without labels" - this plugin will appear in the next release
