### ISSUE TITLE
[Bug] Compatibility for mobile version.

### ISSUE THREAD

**Issue by kyoyacchi** [raingart/Nova-YouTube-extension#34]
*Describe the bug*
None of settings in Nova works in mobile version of YouTube.
Also, Turkish translation looks very bad-translated.

 - Browser: Kiwi Browser 107.0.5304.74 (Official Build) (64-bit)
 - Violentmonkey 2.13.3
 - Nova version: 1.33.2

**Comment by raingart** [comment]
Last time I tested `m.youtube.com` then only ~40% of the plugins were compatible.
Now I don't know the status. I can try part of plugins trying to adapt.
One of the reasons (besides being lazy because I personally don't use the mobile version) is that I need to somehow separate/specify the list of mobile-compatible plugins.

For the translat. You can send me the corrected version. Or I can turn it off completely Turkish localize.
If you want to improve the translation, then look for lines in the `/plugins/` directory that contain these
```:tr':```

**Comment by raingart** [comment]
I partially checked the compatibility
there are two main plugins that change the speed and quality of the video.
To adapt the rest, you need to duplicate some plugins in parallel. 

Send me a list of plugins you would like.

**Comment by raingart** [comment]
List of working plugins of the test ver:

![Screenshot from 2022-11-17 17-55-50](https://user-images.githubusercontent.com/13064767/202494931-7be70b99-0cb5-4765-a3dc-3ddc23c24ac6.png)

![Screenshot from 2022-11-17 17-55-01](https://user-images.githubusercontent.com/13064767/202494948-c8e5edd6-6f59-4405-8bd5-892668050067.png)

The problem is that the module for determining the transition to a new page (lazy loading) does not work.
If you manually reload the page, they start working currect.

I'll try to fix it. If it doesn't work, I will completely disable the work in the mobile ver.
