### ISSUE TITLE
Options page redirects to https://raingart.github.io/

### ISSUE THREAD

**Issue by Akeem29** [raingart/Nova-YouTube-extension#38]
It seems like options page of this extension refuses to work if I use Chromium or Firefox with Persian, Belarusian or Russian language and keep JavaScript enabled, making the extension practically unusable. It automatically redirects a user to the page https://raingart.github.io/ , not allowing one to use options page on https://raingart.github.io/options.html . Running a web-browser with any UI language except those resolves this issue. 

 - Browser: Chromium Version 103.0.5060.53 (Official Build) (64-bit)
 - ...monkey Violentmonkey v2.13.3
 - Nova version: 0.34.0

**Comment by raingart** [comment]
I know. Because of these fagots, I had no light for 3 days.
Yes, this was still ukrainian blocked. But [one guy sent a full translation](/raingart/Nova-YouTube-extension/issues/31). I didn't ask him for it. But once it was ready, I took pity on his work and removed his lang.
Despite the fact that I hate your entire region. Use English or another language. Or many alternatives
