### ISSUE TITLE
[Feature] Disable YouTube 60 FPS (Force 30 FPS)

### ISSUE THREAD

**Issue by jayveegcl** [raingart/Nova-YouTube-extension#40]
Tells YouTube that your browser only supports videos at 30FPS or less, which switches all 60FPS videos to 30FPS and allows old computers to watch high-resolution videos without stutter.

**Comment by raingart** [comment]
I will not implement. This is due to the speed of plugins initialization (it is slower than the init of the player itself). 
[h264ify](https://github.com/erkserkserks/h264ify) does not always work.

It is enough to set the quality to 720p and the result will be the same:
https://greasyfork.org/en/scripts/23329-disable-youtube-60-fps-force-30-fps/feedback

Therefore, using an external script/extension will always be better than a plugin.

I recommend use - [Invidious](https://yewtu.be/)
or [https://github.com/rainart/youtube-to-smplayer](https://github.com/raingart/youtube-to-smplayer#upd-better-alternative)
