### ISSUE TITLE
[Bug] auto pause and stop video preload not working

### ISSUE THREAD

**Issue by Joshua64** [raingart/Nova-YouTube-extension#42]
(I reinstaled 2 times and i made the same configuration and, the same thing :( )

Hello, the video auto pause and stop video preload option don't work, i open one video, any video, and the video loads normally and don't pause, with all or embed configuration set. 

 - Browser: Chrome 108.0.5359.72
 - Tampermonkey 4.18.1
 - Nova version: 0.35.0

**Comment by raingart** [comment]
Problem with a broken save config function
`boolean` value will be saved as `string`

I don't know what caused it. It has not been changed in the latest version.

Has this plugin worked for everyone before?

install [beta ver](https://openuserjs.org/scripts/raingart/Nova_YouTube) 

I fixed 2 plugins (stop and pause video). But it will take time to fix all problem areas

**Comment by Joshua64** [comment]
stop video preload and auto pause now work perfectly with this beta ver. thanks :)

**Comment by raingart** [comment]
The reason turned out to be that I'm testing the script in dynamic expansion mode and not userscript.

And there was no data type [convector](https://github.com/raingart/Nova-YouTube-extension/blob/e5ad91f8d2d32517d168d4c077b02853612a2ba4/js/loader.js#L13-L18) in the userscript

There were some completely inoperative such plugins:
- [playlist-toggle-autoplay]
- [video-stop-preload]
- [video-autopause]
- [rate-wheel]
- [search-query]
- [playlist-duration]
