### ISSUE TITLE
[Feature] Increase playback speed limit

### ISSUE THREAD

**Issue by JSEverything** [raingart/Nova-YouTube-extension#46]
It is already possible to set the playback rate to any number, for example `$("video").playbackRate = 3` in devtools. It would be nice to have a higher upper speed limit as a part of this extension, especially for the mouse wheel speed control.

**Comment by raingart** [comment]
![Screenshot from 2023-01-14 10-27-50](https://user-images.githubusercontent.com/13064767/212463459-c2eae4db-ad9a-4f85-8965-b5e4b56ab39b.png)

**Comment by JSEverything** [comment]
Oh, I though I checked this menu earlier, sorry. But still the speed control with mouse wheel is limited to 2x and the custom indicator (bar-center) is also broken (not centered) on speeds above 2x so I guess this isssue is more of a bug report with the plugins than feature request.

**Comment by raingart** [comment]
There the problem is that initially the script only worked with the youtube API. And there were gaps with the compatibility of some options
After the html5 implementation was added as an alternative
It is triggered if the default values ​​in the Nova settings are greater than 2x or not a multiple of 0.25

see more
https://greasyfork.org/en/scripts/433360-nova-youtube/discussions/116867

**Comment by JSEverything** [comment]
Thanks for the explanation. I will keep the speed control plugin enabled with the hotkey disabled to still have the custom speed options. After using it for some time I noticed that I still prefer `<` and `>` so I'll just stick with that.
