### ISSUE TITLE
[Bug] Stop play channel trailer and Default tab on channel page on a specific channel

### ISSUE THREAD

**Issue by robertgarciakof** [raingart/Nova-YouTube-extension#50]
The options "Stop play channel Trailer and "Default tab on channel page" don't work on this particular channel, but in others channels it does:
https://www.youtube.com/@MoreAlpha
https://www.youtube.com/MoreAlpha

 - Browser: Chrome and Chromium 109.0.5414.120
 - Nova version: 1.36.2

**Comment by raingart** [comment]
I noticed this on other channels. Some channels even before the introduction of the @ prefix had links in the form `https://www.youtube.com/userName`. [ex.](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/other/channel-tab.js#L2-L3)
and I did not find a way to determine that we are now on the channel page.

The [current pagetype](https://github.com/raingart/Nova-YouTube-extension/blob/master/js/plugins.js#L142-L153) definition function is based on the url and parsing it. Trying to define the page by internal htnl elements will break the plugin launcher

Also, some channels have crashes in YouTube itself.
Here open the [link](https://www.youtube.com/@LuBlog/about) and click refresh page

I have looked at the implementation in other projects and they are all based on regex parsing of the page url

I won't fix it because I don't know how. If I were given a list of all existing YouTube page types
I could use the exception method to determine that this is a channel now

but since I myself use the limited capabilities of YouTube and not enough to figure out all a page type.

**Comment by robertgarciakof** [comment]
Ok,  if it can't be done in a better way, it's better not to touch it

**Comment by raingart** [comment]
for pages like you gave an example, you can determine by the presence of uppercase letters.
but this only partly solves the problem

**Comment by robertgarciakof** [comment]
Curious, with these channels with capital letters it is true that they fail when they go without @
https://www.youtube.com/ProTradingSkills
https://www.youtube.com/XboxToday
https://www.youtube.com/ALBO

But at least they work with @
https://www.youtube.com/@ProTradingSkills
https://www.youtube.com/@XboxAhoy
https://www.youtube.com/@ALBO

**Comment by raingart** [comment]
Feature added in beta urlContainsUppercase(without unicode)

This is the maximum that can be done. My opinion is that even youtube itself does not work well without markers indicating that it is now a channel page, and not internal

And in 2 years to change `/c/name` and `/@name` indicates that they themselves don’t know what they are doing
