### ISSUE TITLE
[Bug] Load comments button

### ISSUE THREAD

**Issue by HDark15** [raingart/Nova-YouTube-extension#55]
The load comments button being put too low on the bottom, almost touching the taskbar. I remember it's not the case before

 - Browser: Firefox 110.0 (64-bit)
 - violentmonkey 2.13.10
 - Nova version: 0.37.0

**Comment by raingart** [comment]
install [beta](https://openuserjs.org/scripts/raingart/Nova_YouTube)

If there is a suggestion where it is better to place the button, advise.

Personally I use the plugin "Comments section in popup" is activated, the button appears here

![Screenshot from 2023-02-19 12-16-43](https://user-images.githubusercontent.com/13064767/219941873-95aebbde-1070-4596-95f4-598dc501155b.png)

**Comment by raingart** [comment]
>It's the same code, I usually update it from there

in pointed out 0.37.0` and the current version 0.37.0.2

check now beta

I added a variable to top in code, to change the width. Now the value is 50%.
I don't know if I need to add this parameter to the settings or you can choose which one you like and it will be the default

Opened a section for commenting. And he remembered why he hid it. Block constantly weighs on top. I was too lazy to fix it. Given that almost all the comments on youtube are unhelpful or stupid. It’s a pity that you can’t limit the display of comments only to those who provided a certificate from a psychologist or id-pass.

**Comment by raingart** [comment]
I forgot to ask you if you had to enter "Comments sort" or "Comments popup" . They essentially do the same thing but in different ways.

Comments sort is my own implementation of loading comments using the API. It is limited in the capabilities of the Youtube API itself. And viewing reply and commenting will probably never be available due to quotas

**Comment by raingart** [comment]
"Comments sort" is an implementation of a single user request for the ability to sort comments. I had to implement it this way than to change the current structure that is displayed on the site.

**Comment by raingart** [comment]
it's not impossible. It doesn't really make sense. Technically, the block of comments is replaced by a button for downloading it. This function is generic and can be applied to any element.

Even if you add the ability to position it, you still need to scroll to the bottom of the comments.

That's why the plugin "Comments section in popup" appeared. The solution to wasting time scrolling to the bottom.

>The load comments button

You clearly indicated. That I should apologize. I immediately had a correction in my mind that you mean "Comments section in popup" or "Comment sort"

**Comment by raingart** [comment]
I can increase the size of the button itself. For example

![Screenshot from 2023-02-20 12-30-17](https://user-images.githubusercontent.com/13064767/220083317-3d910fc8-eb14-4c17-ae42-156276550940.png)

But don't move

**Comment by raingart** [comment]
button, I will move nowhere. What is the point of doing this if the comments will always appear in the same place

**Comment by raingart** [comment]
i can enlarge the button but not move it
