### ISSUE TITLE
[Bug] Blocking "shorts" in subscription page does not work

### ISSUE THREAD

**Issue by ganego** [raingart/Nova-YouTube-extension#84]
My subscription page (https://www.youtube.com/feed/subscriptions) gets flooded with those pesky shorts.   
I enabled "Thumbnail filtering" & "Hide shorts" & set the "Min duration in sec" to 61.   
Still have shorts visible.  

Two things:  
1) Do "min duration" and short blocker belong together or are they independend of each other? Because there might be legitimate videos under one minute that are not clickbait 'shorts', so I think they should be separated.    
2) If you detect shorts by duration, may I suggest you use the HTML to detect them? The shorts icon could be detected and then the whole video hidden, see `<ytd-thumbnail-overlay-time-status-renderer class="style-scope ytd-thumbnail" overlay-style="SHORTS" has-icon="">`

 - Browser: FF 111
 - Violentmonkey
 - Nova 0.40.0

Thank you

**Comment by raingart** [comment]
1. in the current version, it defines all videos that have duration indications in the corner of the thumbnail. Since shorts does not display the time, it only works for normal video.
2.  Shorts are searched by url `a#thumbnail[href*="shorts/"]`

[test it](https://gist.github.com/raingart/78814ba8cea71c15ed13bd5c93a23570) - click "RAW"
 should mark shorts with a yellow color. The plugin works for me. And I want to check why it doesn't work for you

UPD - the blue frame will indicate the video that is less than the specified time. 0 - disables search by time

**Comment by ganego** [comment]
Thank you for your effort, though for whatever reason, using your new script and then installing the 'normal' version again solved it and now it works oO

Yellow borders for shorts appear directly once the page is loaded - and with the 'normal' script I never see the shorts.
Blue borders for videos below length x, appear after several seconds - and with the 'normal' script, the videos disappear after several seconds. Not sure if that is intentional, but I don't need that feature anyway.

May I suggest an UI improvement then: Show the "Min duration in sec" option independently from the "shorts" option. Because I was confused about how it works and if I had to now enter a time, because once you enable the "shorts" blocker, the "min duration" pops up. But as you explained, they have nothing to do with each other. And/or make it clear in the help page.

Sorry again for having wasted your time, but thank you very much for creating this addon!

**Comment by raingart** [comment]
>the videos disappear after several seconds
This shouldn't be happening. Perhaps this is the reason this bug. 
Or perhaps you have included both versions of the script. And one of them marks and the other removes the thumbnails

I thought that if the user does not want to watch short videos, then watch shorts too.
I thought that if you leave these 2 options separately, then the user might think that if you set 60 seconds, then this can hide shorts as well. But it's not. Since shors do not display duration in standard ways.

"watch" and "shorts" thumbnails inside are different. For this, 2 different methods are used.
Most likely I will put it in a separate point of limiting the duration. But I will point out that it does not apply to shorts. I think it will be clearer.

Don't apologize. It is obvious that I, as a developer, believe that everything I have done is also clear to all other users. It is obvious that this is not so and many things are not obvious, and require clarification

**Comment by raingart** [comment]
It is worth pointing out that filtering does not occur on all pages. And it's not obvious. Should it be used on the main page? I have attached a screenshot. I hope you understand the launch logic from it.

![Screenshot from 2023-04-24 13-54-39](https://user-images.githubusercontent.com/13064767/233976633-d7d0f424-07ce-4df7-a5d7-b45174886b38.png)

Of course, it would be better to label the video so that the user understands what works and when. But I'm lazy

**Comment by raingart** [comment]
What do you think is the best name?
- Min duration in sec (for regular video)
- Min duration in sec (excluding shorts)


Or any other tips to improve localization

**Comment by raingart** [comment]
I just changed the save format. Now instead of seconds there will be a digital format. As for me, it is less convenient, but more visual. Because not everyone knows that 3600 seconds is 1 hour.
Maybe it's wrong and shouldn't be changed.

![Screenshot from 2023-04-24 14-32-35](https://user-images.githubusercontent.com/13064767/233984834-f0b5896d-d355-4378-9244-0811b637454d.png)

**Comment by ganego** [comment]
> > the videos disappear after several seconds

>This shouldn't be happening. Perhaps this is the reason this bug.
>Or perhaps you have included both versions of the script. And one of them marks and the other removes the thumbnails

No, only one version is running. I replaced the code to be the 'debug' version and then back again.


> I thought that if the user does not want to watch short videos, then watch shorts too.

I don't like "shorts" because they recycle old content for clickbait. I do not want to support this.  
But I also subscribed to channels that might have short videos, that are just regular videos. Those I want to see, because they are new.

> I thought that if you leave these 2 options separately, then the user might think that if you set 60 seconds, then this can hide shorts as well. But it's not. Since shors do not display duration in standard ways.

I think with changing it to "Min duration in sec (for regular video)" it becomes more clear and the option should be always shown when thumbnail filtering is active. Because when it just becomes visible when I enable the "shorts" blocker, then in my mind, it has do something with "shorts".

> Don't apologize. It is obvious that I, as a developer, believe that everything I have done is also clear to all other users. 

I know that feel :)

**Comment by ganego** [comment]
> It is worth pointing out that filtering does not occur on all pages. And it's not obvious. Should it be used on the main page? I have attached a screenshot. I hope you understand the launch logic from it.

Hm that is indeed a tricky question. I never visit the main page, only my subs and maybe a channel page. Of course if you want to go full hardcore, make an options matrix (like a table with checkboxes) for everything.  
I only use the "shorts" blocker, because I want to see everything else, so no idea really what would be the best solution
