### ISSUE TITLE
[Bug] No available options

### ISSUE THREAD

**Issue by Fred-Vatin** [raingart/Nova-YouTube-extension#88]
_Note! Try updating/reinstalling the extensions. Maybe this will help._

I did. I even deleted all the content of user_settings.
![image](https://github.com/raingart/Nova-YouTube-extension/assets/22337329/0c42e5a1-ff1b-4297-996f-4ac9a0328633)

I restarted the browser to no avail.

# Describe the bug

 - Browser: Firefox 114.0.2 (64 bits)
 - Tampermonkey 4.18.1
 - Nova 0.41.0

When I click the nova button to go to options, the plugins tab is empty. It used to work. I have no idea what happened other than a browser update.
![Options page](https://github.com/raingart/Nova-YouTube-extension/assets/22337329/5ba1fd0b-1771-4d2e-b6ec-d43d106517c5)

Same for the map
![Map](https://github.com/raingart/Nova-YouTube-extension/assets/22337329/d46809b6-9c61-442d-8ff0-3aa3ee8d3893)

The other tab is ok.
![other](https://github.com/raingart/Nova-YouTube-extension/assets/22337329/73dcf2f2-c0d1-421c-9444-abd90469195d)

Here is the full console log when opening https://raingart.github.io/options.html?tabs=tab-plugins
![image](https://github.com/raingart/Nova-YouTube-extension/assets/22337329/f79097fb-09cd-40fa-877a-51cdc154a178)

**Comment by Fred-Vatin** [comment]
Solved by installing the 0.41.9 version available here https://openuserjs.org/scripts/raingart/Nova_YouTube

**Comment by BobbyWibowo** [comment]
> Solved by installing the 0.41.9 version available here https://openuserjs.org/scripts/raingart/Nova_YouTube

Can confirm it works after the update, thanks

Gosh, OpenUserJS' rate limit whatever is so god awful, Violentmonkey couldn't ever auto update, ever

**Comment by raingart** [comment]
I finally solved the main problem due to which some of the blessings were removed. Previously, the settings from the most recently uploaded plugins on github were displayed. Now they display exactly the locally installed version.

I uploaded to [openuserjs](https://openuserjs.org/scripts/raingart/Nova_YouTube) all available plugins.
Yesterday I tried to make a script and fix the existing problems. But failed. I'll try to finish it today.
Some of the plugins conflict. part of the functionality is disabled. I know the settings page is broken. There were attempts to make both versions work, but unsuccessfully.

The notification module is incomplete. And I thought that since the number of plugins has been unchanged for a couple of months, few people will go to the settings page and not notice that settings page has stopped working.
