### ISSUE TITLE
more than 100 comments in comment sort?

### ISSUE THREAD

**Issue by NotWaveWayz** [raingart/Nova-YouTube-extension#96]
custom number limit or max? and/or loading more comments when scrolling down?

**Comment by raingart** [comment]
I will think about it.
The restriction is due to limits on 1 request. Several requests are needed.

**Comment by raingart** [comment]
You may be interested in additional details:
Query takes "Top 100" according to youtube comments. Sometimes, due to 100 comments, much less is displayed

![Screenshot_5](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/c674aad0-8a96-45c4-bee0-afe5e58ba218)

Also not accessible via the API are comments that have been deemed objectionable. You may have noticed that the youtube comment counter does not match the number of comments. They are under moderation. That is, it is impossible to get really all the comments.

To get replies, you need a separate request for each comment.
Everything comes down to limits. User API Key is likely to be required

maybe [other alternatives](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/comments/sort.js#L35-L36) I found will satisfy you

**Comment by NotWaveWayz** [comment]
thanks for the info!
was hoping this would be possible as YCS has seemly not been maintained in a while and has some annoying bugs.
i guess ill look into alt2

**Comment by raingart** [comment]
I entered into the search. Perhaps something from this list will suit you.
https://github.com/topics/youtube-comments

this project caught my eye
https://github.com/FreeTubeApp/yt-comment-scraper

my current implementation was not designed for multiple requests. I will try to implement but without hope of success

**Comment by raingart** [comment]
I rewrote. If there is no key, then the limit is 500 comments.
There are no limits with the key. But I did not test where there are hundreds of thousands of comments. Most likely there will be gaps. In fact, I didn't test it at all. If there are questions ask.

ps Calls are asynchronous in one thread. The more comments, the longer. In case of failure, the uploaded comments will not be displayed. One thread for YouTube to be unbanned.

https://openuserjs.org/scripts/raingart/Nova_YouTube
ps use only 1 active Nova nstance (beta or stable) i to avoid crash

**Comment by raingart** [comment]
Tested on [most known to me video with a lot of comments](https://www.youtube.com/watch?v=dQw4w9WgXcQ). It turned out that YouTube itself is causing a crash. And only one and a ~1500 comments are loaded. So maybe it makes sense for you to look for other alternatives that can handle load more .

in the image above, the reason for the loading to stop is the lack of data about the next page with comments

![Screenshot from 2023-07-30 14-23-59](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/1c824820-c87b-4318-84f4-59b584362a87)
