### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#99]
1.43.0 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

Hiding the share button and thanks button does not work for me

**Comment by zkisaboss** [comment]
by the way I'm using the chrome extension

**Comment by raingart** [comment]
hi @zkisaboss

try to update. Or switch to the userscript ver to receive updates in a timely manner. At the moment, finally, the settings page displays the parameters taken from the local (installed ver) of the user.

about the current issue, unfortunately, since version 1.43.0 and before the current one, there were no updates that would change the indicated buttons:
https://github.com/raingart/Nova-YouTube-extension/commits/master/plugins/details/buttons.js
In the current implementation, the plugin does not affect the items that are hidden in the dropdown menu

There is a possibility that your template is different from the version that is available to me. Youtube for different regions may run separate test functions. Try to send me the html code of this block `ytd-watch-metadata #actions` so that I can see if the paths of the elements have not changed

**Comment by zkisaboss** [comment]
I tested the latest version (1.43.4) on my Mac and found that autopause works only when switching between two fullscreen windows. However, when I switch between applications in the same window, the YouTube video doesn't pause automatically. Switching tabs also doesn't work, it only pauses the original tab when I start playing the video in the new tab.

**Comment by zkisaboss** [comment]
I'm not sure how to propperly find the html of the code block. What seems to be the block of code is too large to send in a comment. I tested in version 1.43.1

I think the problem is that HTML elements change depending on screen size and page zoom.

**Comment by zkisaboss** [comment]
This fix actually works really nicely, thanks for the resources too. I'm learning js and am really inspired by your userscript :)

**Comment by raingart** [comment]
I personally really liked this [userscript](https://github.com/Taraflex/ranobe-ebook-loader/tree/master/src). It is concise and easily extensible. 
But I chose a different way, more optimized.

My recommendation is a quote from one of the books - "it is better to choose the right architecture with bad code. Than good code but bad architecture."
